import { useEffect, useMemo, useState } from "react";
import { useGenerateDeep } from "@/client/hooks/useCards";
import type { BoundaryTest, BoundaryTestOption, Card } from "@/shared/types";
import { SchemaBlockageSvgProto } from "./SchemaBlockageSvgProto";
import { SchemaBalanceSvgProto } from "./SchemaBalanceSvgProto";
import { SchemaContainerSvgProto } from "./SchemaContainerSvgProto";
import { SchemaLinkSvgProto } from "./SchemaLinkSvgProto";
import { SchemaPathSvgProto } from "./SchemaPathSvgProto";
import "./prototype-word-card.css";

// ---------------------------------------------------------------------------
// Sanitize AI-generated SVG: strip dangerous elements/attributes
// ---------------------------------------------------------------------------
function sanitizeSvg(raw: string): string | null {
  if (!raw || !raw.includes("<svg")) return null;
  // Remove <script>, <foreignObject>, event handlers, <image> with external href
  let svg = raw
    .replace(/<script[\s\S]*?<\/script>/gi, "")
    .replace(/<foreignObject[\s\S]*?<\/foreignObject>/gi, "")
    .replace(/<image[^>]*>/gi, "")
    .replace(/\bon\w+\s*=\s*["'][^"']*["']/gi, "")
    .replace(/javascript\s*:/gi, "");
  // Ensure it starts with <svg and ends with </svg>
  const start = svg.indexOf("<svg");
  const end = svg.lastIndexOf("</svg>");
  if (start === -1 || end === -1) return null;
  svg = svg.slice(start, end + 6);
  return svg;
}


interface NormalizedBoundaryTest {
  sentence: string;
  options: BoundaryTestOption[];
}

function normalizeBoundaryTests(tests: BoundaryTest[]): NormalizedBoundaryTest[] {
  return tests.map((t) => {
    if (t.sentence && t.options && t.options.length > 0) {
      return { sentence: t.sentence, options: t.options };
    }
    return {
      sentence: t.scenario ?? "",
      options: [
        {
          verdict: (t.answer === "yes"
            ? "yes"
            : t.answer === "no"
              ? "no"
              : "maybe") as "yes" | "no" | "maybe",
          word: "—",
          reason: t.explanation ?? "",
        },
      ],
    };
  });
}

function hasDeepData(card: Card): boolean {
  const fam = card.familyComparison;
  const tests = card.boundaryTests;
  const schema = card.schemaAnalysis;
  return (
    !!schema ||
    (Array.isArray(fam) && fam.length > 0) ||
    (Array.isArray(tests) && tests.length > 0)
  );
}

function BoundaryTestItem({ test }: { test: NormalizedBoundaryTest }) {
  const [revealed, setRevealed] = useState(false);

  return (
    <div className="test-item">
      <div className="test-blank">
        {test.sentence.split("______").map((part, i, arr) => (
          <span key={i}>
            {part}
            {i < arr.length - 1 && (
              <span className="blank" aria-hidden="true">
                ______
              </span>
            )}
          </span>
        ))}
      </div>

      {!revealed && (
        <button
          type="button"
          className="reveal-btn"
          onClick={() => setRevealed(true)}
        >
          显示答案
        </button>
      )}

      <div className={`test-options${revealed ? " visible" : ""}`}>
        {test.options.map((opt, i) => (
          <div key={i} className="opt">
            <span className={`verdict ${opt.verdict}`}>
              {opt.verdict === "yes" ? "✓" : opt.verdict === "no" ? "✗" : "?"}
            </span>
            <span className="word-choice">{opt.word}</span>
            <span className="reason">— {opt.reason}</span>
          </div>
        ))}
      </div>
    </div>
  );
}

export function PrototypeWordCard({ card, onClose }: { card: Card; onClose?: () => void }) {
  const generateDeep = useGenerateDeep();

  const deepCard = generateDeep.data ? { ...card, ...generateDeep.data } : card;

  const shouldAutoGenerateDeep = useMemo(() => !hasDeepData(deepCard), [deepCard]);

  // Auto-generate deep layer on open to match the prototype experience.
  useEffect(() => {
    if (!shouldAutoGenerateDeep) return;
    if (generateDeep.isPending || generateDeep.data) return;
    generateDeep.mutate(card.id);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [card.id, shouldAutoGenerateDeep]);

  const posLabels = deepCard.pos
    ? deepCard.pos.split(/[,/]/).map((p) => p.trim()).filter(Boolean)
    : [];

  const schemaType = deepCard.schemaAnalysis?.coreSchema?.toLowerCase();
  const coreImageText =
    deepCard.schemaAnalysis?.coreImageText || deepCard.schemaAnalysis?.coreSchema;
  const customSvg = useMemo(
    () => sanitizeSvg(deepCard.schemaAnalysis?.coreSvg ?? ""),
    [deepCard.schemaAnalysis?.coreSvg],
  );

  const evolutionChain = deepCard.schemaAnalysis?.etymologyChain;

  const scenes = deepCard.schemaAnalysis?.sceneActivation ?? [];

  const family = deepCard.familyComparison ?? [];

  const boundaryNote =
    (deepCard.schemaAnalysis as (typeof deepCard.schemaAnalysis) & {
      familyBoundaryNote?: string;
    })?.familyBoundaryNote;

  const tests = deepCard.boundaryTests
    ? normalizeBoundaryTests(deepCard.boundaryTests)
    : [];

  return (
    <div className="proto-page">
      <div className="card">
        {/* Close button */}
        {onClose && (
          <button
            type="button"
            className="close-btn"
            onClick={onClose}
            aria-label="Close"
          >
            ✕
          </button>
        )}
        {/* 1. Word header — single line */}
        <header className="word-header">
          <h1>{deepCard.word}</h1>
          {deepCard.ipa && <span className="ipa">{deepCard.ipa}</span>}
          <div className="chips">
            {posLabels.map((p) => (
              <span key={p} className="chip accent">
                {p}
              </span>
            ))}
            {deepCard.cefr && <span className="chip">CEFR {deepCard.cefr}</span>}
            {deepCard.wad != null && (
              <span className="chip">WAD {deepCard.wad.toFixed(1)}</span>
            )}
            {deepCard.wap != null && (
              <span className="chip">WAP {deepCard.wap.toFixed(1)}</span>
            )}
          </div>
        </header>

        {/* 2. Core image — custom SVG or fallback template */}
        {deepCard.schemaAnalysis && (
          <section className="core-image">
            <h2>核心意象 Core image</h2>

            {customSvg ? (
              <div
                className="custom-schema-svg"
                dangerouslySetInnerHTML={{ __html: customSvg }}
              />
            ) : (
              <>
                {schemaType === "blockage" && <SchemaBlockageSvgProto />}
                {schemaType === "container" && <SchemaContainerSvgProto />}
                {schemaType === "path" && <SchemaPathSvgProto />}
                {schemaType === "link" && <SchemaLinkSvgProto />}
                {schemaType === "balance" && <SchemaBalanceSvgProto />}
              </>
            )}

            {coreImageText && <p>{coreImageText}</p>}
          </section>
        )}

        {/* Deep layer loading / error — top-level so it's always visible */}
        {generateDeep.isPending && (
          <div className="deep-loading">
            <span className="deep-spinner" />
            正在生成深度分析…
          </div>
        )}

        {generateDeep.isError && (
          <div className="deep-error">
            深度分析生成失败：{generateDeep.error.message}
          </div>
        )}

        {/* 3. Etymology */}
        {deepCard.etymology && (
          <section className="etymology">
            <h2>词根词源 Etymology</h2>
            <p>{deepCard.etymology}</p>
            {evolutionChain && evolutionChain.length > 0 && (
              <div className="evolution-chain">
                {evolutionChain.map((stage, i) => (
                  <span key={i}>
                    {i > 0 && <span className="arrow">→</span>}
                    <span className="stage">{stage}</span>
                  </span>
                ))}
              </div>
            )}
          </section>
        )}

        {/* 4. Scene activation — collapsible */}
        {scenes.length > 0 && (
          <details className="tests-toggle">
            <summary className="tests-summary">
              <span className="chevron">&#9654;</span> 场景激活 Frame activation
            </summary>
            <div className="tests-body">
              {scenes.map((scene, i) => (
                <div key={i} className="scene">
                  <h3>{scene.title}</h3>
                  <p>{scene.description}</p>
                  <p
                    className="scene-example"
                    dangerouslySetInnerHTML={{
                      __html: scene.example.replace(
                        /\*\*(.*?)\*\*/g,
                        "<strong>$1</strong>",
                      ),
                    }}
                  />
                  {scene.associatedWords.length > 0 && (
                    <div className="associated-words">
                      {scene.associatedWords.map((w) => (
                        <span key={w}>{w}</span>
                      ))}
                    </div>
                  )}
                </div>
              ))}
            </div>
          </details>
        )}

        {/* 5. Family comparison — collapsible */}
        {family.length > 0 && (
          <details className="tests-toggle">
            <summary className="tests-summary">
              <span className="chevron">&#9654;</span> 家族对比 Family comparison
            </summary>
            <div className="tests-body">
              <div className="table-scroll">
                <table className="family-table">
                  <thead>
                    <tr>
                      <th>词</th>
                      <th>核心区别</th>
                      <th>情感 / 语域</th>
                      <th>典型场景</th>
                    </tr>
                  </thead>
                  <tbody>
                    {family.map((entry) => (
                      <tr
                        key={entry.word}
                        className={
                          entry.word.toLowerCase() === deepCard.word.toLowerCase()
                            ? "highlight"
                            : ""
                        }
                      >
                        <td className="word-col">{entry.word}</td>
                        <td>{entry.distinction}</td>
                        <td>{entry.register}</td>
                        <td>{entry.typicalScene}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
              {boundaryNote && (
                <div
                  className="boundary-note"
                  dangerouslySetInnerHTML={{ __html: boundaryNote.replace(/\n/g, "<br>") }}
                />
              )}
            </div>
          </details>
        )}

        {/* 6. Boundary tests (collapsed, answers hidden) */}
        {tests.length > 0 && (
          <details className="tests-toggle">
            <summary className="tests-summary">
              <span className="chevron">&#9654;</span> 边界测试 Boundary tests
            </summary>
            <div className="tests-body">
              {tests.map((t, i) => (
                <BoundaryTestItem key={i} test={t} />
              ))}
            </div>
          </details>
        )}
      </div>
    </div>
  );
}
